version: '3.3'
services:
  mysql: 
    container_name: mysql-cockatoo
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
  redis:
    container_name: redis-cockatoo
    image: redis
    ports:
      - '6380:6379'
    restart: always